### PR TITLE
Add stack ssh command

### PR DESCRIPTION
**Pull request by aptomaKetil**
Add convenience function for SSH'ing into a given stack. Uses the CodeDeploy config to find the correct ASG based on deployment group names, and proxies a SSH connection.

### CODE REVIEW

**Comment by martinj** [comment]
Its a bit weird having this under stack because its actually using a DeploymentGroup and `deploy` config which doesn't have a connection to stacks.

**Comment by martinj** [comment]
I think we should consider add some sort of connection to the actually stacks in the stack configs because its been a bit of annoyance having to remember the stack names when updating/creating.

Something out of the top of my head:
Add a stack id tag to CF that allows us to list/view stacks bound to a config?

**Comment by aptomaKetil** [comment]
How about just `amp ssh`? I don't want to put it under deployment (`amp deploy ssh production`??).

**Comment by martinj** [comment]
Are you think something along the lines `amp ssh deployment production`? Because i would like to have the same feature if we fix stacks.

**Comment by aptomaKetil** [comment]
I'm thinking `amp ssh <deployment group>` as the default, using CodeDeploy. If you need to SSH based on stack name/ID, you'd specify that with additional options.

**Comment by martinj** [comment]
I would prefer to have it more explicit for consistency. All other commands are `amp <type> <action>`

**Comment by aptomaKetil** [comment]
You're thinking `amp ssh deployment production` for connections via CodeDeploy, and `amp ssh stack <something>` for the other case?

If so, I'd say that 99% of the time, we just want to connect to a prod/dev instance, and we should optimize for that use case.

**Comment by martinj** [comment]
I get your point, but the inconsistency is a _non_ optimisation, at least me.

**Comment by aptomaKetil** [comment]
Alright, let's err on the side of consistency. `amp ssh deployment production` it is.

**Pull request merged**
