### PR TITLE
Add shim for array.prototype.find

### LINKED ISSUE #7: array.find not found in some combos of node
Please use array.filter instead of find, in lib/config.js, as at least in my case, the find method is not found.

### PR DESCRIPTION
**Pull request by gunnarlium**
Fix #7

### CODE REVIEW

**Comment by gunnarlium** [comment]
Looks like this fix isn't quite working ...

**Comment by martinj** [comment]
Ok, any errors?

**Comment by stefangrunert** [comment]
adding unneccesary depenencies for simple programming tasks should be avoided

**Comment by gunnarlium** [comment]
I'm still getting the same error, so looks like the polyfill isn't applied properly. Probably better to rewrite to use vanilla ES5 until Lamda is ready for Node 4.

**Pull request merged**
