### PR TITLE
Log command

### PR DESCRIPTION
**Pull request by martinj**
Not sure i this should be `amp log get` command.
Here is an alternative suggestion `amp s3 get`.

Im open for suggestions.

### CODE REVIEW

**Comment by haakond** [comment]
Just to manage the expectations right; amp cli is meant to be a helper tool for the developers?

I think that for the use case "retrieve logs for analyzing" "amp log get" is simple and to the point.

For the use case "retrieve any file from S3" I think s3cmd would be best to use directly, since it has more advanced options available and wouldn't be used that often.

**Comment by gunnarlium** [comment]
Agree with Håkon that `amp log get` is a better description of what this does. The fact that it uses S3 is an implementation detail.

**Comment by martinj** [comment]
> amp log get is a better description of what this does

The readme presents the use case for logs but it could be used for syncing a path as well e.g

`amp log get -u s3://buck/myfiles -o myfiles`

**Comment by gunnarlium** [comment]
I think I'd prefer that to be a hidden feature or a "hack", and rather add an additional command for syncing, if that's needed.

**Comment by martinj** [comment]
Okidoki. 

Made some final adjustments.
Ready for review.

**Pull request merged**
