### PR TITLE
[lamda] Add support for setting runtime

### PR DESCRIPTION
**Pull request by gunnarlium**
Runtime will be read from lambda options when creating a function.

To update an existing function, you need to run the new command `amp lambda update-config`.

This will possibly also add support for managing Java and Python based functions with this CLI, though I have not tested that.

### CODE REVIEW

**Comment by martinj** [comment]
We've gone a bit to far with to few tests.
Can you add some tests to the new functionality?

**Comment by gunnarlium** [comment]
Can do!

As the runtime will not be changed during code update, I'll also change to make Nodejs4.3 the default.

**Comment by martinj** [comment]
Great!

**Comment by gunnarlium** [comment]
Tests added.

Was a bit unsure of whether to Mock the AWS SDK or the network. Did network first, but that doesn't give very helpful error messages. As we won't really be able to verify that we're using the API correctly without actually sending requests anyway, I think it's better to mock the SDK.

**Comment by martinj** [comment]
I have mostly done mocking on network for aws-sdk.
It's been very helpful since it does a lot of validation before it actually sends the request.
In what way do you think it doesn't give very helpful error messages?

**Comment by gunnarlium** [comment]
May be caused by the strategy I took. I specified the expected request body with nock, and didn't get any other error than unexpected network call, unless the body matched perfectly.

**Comment by gunnarlium** [comment]
Updated with better use of Nock.

**Comment by martinj** [comment]
Great job!

**Pull request merged**
